# SPDX-License-Identifier: MIT-0
---
# tasks file for vscode

- name: Import microsoft key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ vscode_microsoft_rpm_key_url }}"

- name: Install vscode repo file
  ansible.builtin.copy:
    src: vscode.repo
    dest: "{{ vscode_yum_repo_file_dest }}"
    mode: '0644'

- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    state: present
    update_cache: true
